language: node_js
node_js:
  - "12"
branches:
  only:
  - master # auto build and deploy in only master branch
install:
  - yarn install
  - yarn add -D firebase-tools

script:
  - yarn lint
  - yarn generate
after_success:
- firebase use --token ${FIREBASE_TOKEN} # set firebase token
- firebase use --add ${PROJECT_ID} # set current project
- firebase target:apply hosting mumspquest mumspquest
- firebase deploy --non-interactive --only hosting:mumspquest --token "${FIREBASE_TOKEN}" # deploy project